version: '3.7'
services:
  wildzone-database-suppliers:
    image: mysql
    networks:
      - database-suppliers
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: wildzone
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d

  wildzone-db-admin-suppliers:
    image: phpmyadmin/phpmyadmin
    networks:
      - database-suppliers
    ports:
      - 8080:80
    environment:
      PMA_HOST: wildzone-database-suppliers
    depends_on:
      - wildzone-database-suppliers
networks:
  database-suppliers:
